apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # If your Ingress controller requires a different ingress class, change 'nginx'
spec:
  rules:
  - host: tic-tac-toe.example.com  # REPLACE with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tic-tac-toe
            port:
              number: 80
