apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe               # Service name
  labels:
    app: tic-tac-toe              # Label for organization / selection

spec:
  # Default type is ClusterIP (internal only), so it’s omitted here.
  ports:
    - port: 80                    # External port exposed by the Service
      targetPort: 80              # Port on the Pods the traffic is routed to
      # protocol: TCP            # TCP is default, so this line is optional

  selector:
    app: tic-tac-toe              # Routes traffic to Pods with this label
