# A simplified and cleaner version of the Service manifest
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe      # The name of this Service object
  labels:
    app: tic-tac-toe    # A label to help organize and select this Service
spec:
  # 'type: ClusterIP' is default, so it's omitted for brevity.
  # This Service will only be reachable from within the Kubernetes cluster.
  ports:
  - port: 80              # The port the Service will listen on
    targetPort: 80        # The port on the Pods to forward traffic to
    # 'protocol: TCP' is the default and can be omitted.
  selector:
    app: tic-tac-toe      # Forwards traffic to any Pod with this exact label
